spring:
  application:
    name: EventClean

#  datasource:
#    url: ${DATABASE_URL}
#    driver-class-name: org.postgresql.Driver
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdeb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
